# Mandatory settings

name: Jais Cheema
paginate: 25
url: https://jaischeema.com
blog_theme: light

# Optional settings

about_enabled: true
ga_analytics: 'UA-27359508-1'
discus_identifier:
local_fonts: false
rss_enabled: true
scrollappear_enabled: true
tag_nav_enabled: false
theme_toggle: false
social:
  github: jaischeema
  linkedin: jais-cheema-79400724
  twitter: jaischeema
  email: sayhi@jaischeema.com

# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
